#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-added-large-files" },
    { id = "check-docstring-first" },
    { id = "check-merge-conflict" },
    { id = "check-json" },
    { id = "check-toml" },
    { id = "check-yaml" },
    { id = "end-of-file-fixer" },
    { id = "no-commit-to-branch" },
    { id = "trailing-whitespace", args = [
        "--markdown-linebreak-ext",
        "md",
    ] },
    { id = "check-case-conflict" },
]

[[repos]]
repo = "https://github.com/DavidAnson/markdownlint-cli2"
rev = "v0.23.2"
hooks = [
    { id = "markdownlint-cli2", args = [
        "--config",
        ".markdownlint-cli2.yaml",
    ], language_version = "26.5.0" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.49.0"
hooks = [{ id = "typos", args = ["--force-exclude"] }]

[[repos]]
repo = "https://github.com/alessandrojcm/commitlint-pre-commit-hook"
rev = "v9.26.0"
hooks = [
    { id = "commitlint", stages = [
        "commit-msg",
    ], additional_dependencies = [
        "@commitlint/config-conventional",
    ] },
]

[[repos]]
hooks = [
    { id = "biome-check", exclude = { glob = [
        "**/mvp.css",
        "**/worker-configuration.d.ts",
        "_infra/UptimeMonitor/dist/**",
    ] } },
]
repo = "https://github.com/biomejs/pre-commit"
# when updating this version, remember to also update `$schema` in `biome.jsonc`
rev = "v2.5.10"

[[repos]]
repo = "https://github.com/kjanat/actionlint"
rev = "v1.12.0"
hooks = [
    { id = "actionlint" },
]

[[repos]]
repo = "https://github.com/antonbabenko/pre-commit-terraform"
rev = "v1.108.1"
hooks = [
    { id = "terraform_fmt", files = "^_infra/", args = [
        "--hook-config=--tf-path=tofu",
    ] },
    { id = "terraform_validate", files = "^_infra/", args = [
        "--hook-config=--tf-path=tofu",
        "--hook-config=--tf-init-args=-backend=false",
        "--hook-config=--tf-init-args=-reconfigure",
    ] },
    { id = "terraform_tflint", files = "^_infra/" },
    { id = "terraform_trivy", files = "^_infra/" },
]
